name: Release to Space

on:
  release:
    types: [published]

jobs:
  push-to-space:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deta Space Deployment Github Action
        uses: neobrains/space-deployment-github-action@v0.4
        with:
          access_token: ${{ secrets.DETA_ACCESS_TOKEN }}
          project_id: ${{ secrets.DETA_PROJECT_ID }}
          space_release: true
          list_on_discovery: false
          release_version: ${{ vars.GITHUB_REF }}