name: Push/release to Deta Space

on:
  push:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push-to-space:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deta Space Deployment Github Action
        uses: neobrains/space-deployment-github-action@v0.4
        with:
          access_token: ${{ secrets.DETA_ACCESS_TOKEN }}
          project_id: ${{ secrets.DETA_PROJECT_ID }}
          # Push on push to main branch
          space_push: ${{ github.event_name == "push" }}
          # Release if the is a release
          space_release: ${{ github.event_name == "release" }}
          list_on_discovery: false
          release_version: ${{ github.event.release.tag_name }}